library('DBI')
library('plyr')
library('dplyr')
library('ggplot2')
library('pitchRx')
library('RSQLite')
db <- src_sqlite("pitchRx.sqlite3", create = TRUE)
scrape(start = "2008-01-01", end = Sys.Date() - 1, connect = db$con)
files <- c("inning/inning_hit.xml", "miniscoreboard.xml", "players.xml")
scrape(start = "2008-01-01", end = Sys.Date() - 1, suffix = files, connect = db$con)
